module.exports = {
    // Errors
    COMMON_ERROR: "Error, Please try again.!",
    EMAIL_ALREADY_EXIST: "Email already exists.",
    GUEST_ALREADY_EXIST: "Guest already exists.",
    ADMIN_ALREADY_LOGIN:"Please Logout From Other Device.",
    // Success
    USER_SIGNUP_GUEST: "Guest Create successfully.",
    GUEST_LOGIN: "Guest Login successfully.",
    USER_SIGNUP: "Player Create successfully.",
    USER_NUMBER: "Welcome to the Teen Patti Game.",
    USER_SIGNUP_NUMBER: "User Create successfully.",
    LOGIN_SUCCESS: "Player Login Successfully",
    DAILY_REWORD: "Get Daily Reword Successfully",
    UPDATE_USER: "Update Chips Successfully!",
    SHOP_SUCCESS: "Shop Details Successfully!",
    AD_REWORD_SUCCESS: "Ad Reword Get Successfully!",
    FRIEND_LIST: "Friend List Get Successfully!",
    LOG_OUT: "Player Log Out Successfully!",

    //Game
    ALREADY_IN_ROOM: "Player Already In Room!",
    ROOM_NOT_FOUND: "Room Not Found!",
    PLAYER_NOT_FOUND: "Player Not Found!",
    ROOM_CLOSE: "Room Close",
    SIDE_SHOW_REQUEST_DECLINE: "Side Show Request Decline!",
    SIDE_SHOW_WIN: "You have won the side show, you have ",
    SIDE_SHOW_LOSE: " has won the side show, player has ",
    SHOW_WIN: "You have won this round.",
    SHOW_LOSE: " has won this round.",
    ALL_PACK_WIN: "All Pack You Winner.",
    ENTRY_AMOUNT: "Get Amount Successfully",
    TABLE_SHOW_WIN: "Pot Limit Exceeded. Forced Show.",

    //Game Play
    WAITING_ANOTHER: "Waiting For Another Player..",
    NEW_ROUND: "Starting new round...",
    COLLECTING_BOOT_AMOUNT: "Collecting boot amount of ",
    DISTRIBUTE_CARD: "Distributing cards to players...",
    VARIATIONS_SELECTION: "IS SELECTING THE VARIATIONS.",
    LUDO_SUCCESS: "Lets Start Game Play.",
    LUDO_LIMIT_ERROR: "Your Chips is low Please try again!",

    //otp
    OTP: "Send Otp Successfully",
    OTP_NOT_SEND: "Otp Not Send Please Check Number!",
    SEND_OTP: "Please Send otp",
    EXPIRY_OTP: "Otp Expired Please try again!",
    OTP_WRONG: "Otp Wrong Please try again!",
    OTP_SUCCESS: "Otp Verify Successfully",

    //Room
    PLAYER_SEEN_CARD: "Player Card Seen",

    //Admin
    ADMIN_LOGIN: "Admin Login Successfully",
    ADMIN_ERROR: "Email and Password Invalid!",
    PLAYER_GET: "Player Get Successfully",
    GET_ROOM: "Room Get Successfully",
    CREATE_SHOP: "Shop Create Successfully",
    UPDATE_SHOP: "Shop Update Successfully",
    DELETE_SHOP: "Shop Delete Successfully",
    WIN_LESS_SUCCESS: "Win Less Percentage Details Successfully!",
    CREATE_WIN_LESS: "Win Less Percentage Create Successfully",
    UPDATE_WIN_LESS: "Win Less Percentage Update Successfully",
    DELETE_WIN_LESS: "Win Less Percentage Delete Successfully",
    PLAYER_BLOCK: "Player Blocked Successfully",
    PLAYER_UNBLOCK: "Player Unblocked Successfully",
    UPDATE_AD_REWARDED: "Update Ad Reward Successfully!",
    DAILY_REWARD_SUCCESS: "Daily Reward Details Successfully!",
    CREATE_DAILY_REWARD: "Daily Reward Create Successfully!",
    UPDATE_DAILY_REWARD: "Daily Reward Update Successfully!",
    DELETE_DAILY_REWARD: "Daily Reward Delete Successfully!",
    APP_VERSION_SUCCESS: "App Version Fetched Successfully!",
    CREATE_APP_VERSION: "App Version Create Successfully!",
    UPDATE_APP_VERSION: "App Version Update Successfully!",
    DELETE_APP_VERSION: "App Version Delete Successfully!",
    WELCOME_CHIPS_SUCCESS: "Welcome Chips Fetched Successfully!",
    CREATE_WELCOME_CHIPS: "Welcome Chips Created  Successfully!",
    UPDATE_WELCOME_CHIPS: "Welcome Chips Updated  Successfully!",
    DELETE_WELCOME_CHIPS: "Welcome Chips Deleted  Successfully!",
    NEW_FEATURE_SUCCESS: "New Feature Fetched Successfully!",
    CREATE_NEW_FEATURE: "New Feature Created Successfully!",
    UPDATE_NEW_FEATURE: "New Feature Updated Successfully!",
    DELETE_NEW_FEATURE: "New Feature Deleted Successfully!",
    PLAYER_UPDATE_CHIPS_SUCCESS: "player Update Chips Fetched Successfully!",
    COUNT_FETCHED_SUCCESS: "Count Data Fetched Successfully!",
    LIVE_NOTIFICATION_SUCCESS: "Live Notification Fetched Successfully!",
    CREATE_LIVE_NOTIFICATION: "Live Notification Created Successfully!",
    UPDATE_LIVE_NOTIFICATION: "Live Notification Updated Successfully!",
    DELETE_LIVE_NOTIFICATION: "Live Notification Deleted Successfully!",
    PAYMENT_HISTORY_SUCCESS: "Payment History Fetched Successfully!",
    CREATE_PAYMENT_HISTORY: "Payment History Created Successfully!",
    WEBSITE_DETAIL_SUCCESS: "Website Detail Fetched Successfully!",
    UPDATE_WEBSITE_DETAIL: "Website Detail Updated Successfully!",
    VERIFY_SUCCESS: "Verification Number is Verified successfully!",
    LUDO_SERVER_UPDATE: "Ludo Server Password Updated successfully!",
    ADMIN_UPDATE: "Admin Profile is Updated successfully!",
    DELETE_PLAYER: "Player is Deleted Successfully!",
    DELETE_PLAYERS: "Players are Deleted Successfully!",
    ADMIN_SUCCESS: "Admin Fetched Successfully!",
    TABLE_LIMIT_SUCCESS: "Table Limit Fetched Successfully!",
    CREATE_TABLE_LIMIT: "Table Limit Created Successfully!",
    UPDATE_TABLE_LIMIT: "Table Limit Updated Successfully!",
    DELETE_TABLE_LIMIT: "Table Limit Deleted Successfully!",
    DELETE_PLAYER_UPDATE_CHIPS: "Player Update Chips Deleted Successfully!",
    DELETE_ADMIN_LOG: "Admin Logs Deleted Successfully!",
    DELETE_PAYMENT_HISTORY: "Payment History Deleted Successfully!",
    UPDATE_PLAYER_AD_FREE: "Update Player Ad Free Updated Successfully!",
    ADMIN_MESSAGE_SUCCESS: "Admin Message Fetched Successfully!",
    UPDATE_ADMIN_MESSAGE: "Admin Message Updated Successfully!",
    ADMIN_LOGOUT: "Admin Logged out successfully!",
    DELETE_TEENPATTI_ROOM: "TeenPatti Room Deleted Successfully!",
    DELETE_LUDO_ROOM: "Ludo Room Deleted Successfully!",
    GET_LUDO_ROOM: "Ludo Room fetched Successfully",
}
